### ISSUE TITLE
How to ignore all bots except one

### ISSUE THREAD

**Issue by Zoom-Developer** [Rei-x/discord-speech-recognition#40] opened 2022-09-02 10:12 UTC
I need my bot to ignore all bots except for one of mine. I could not find this functionality not in discord.js, not in this library

**Comment by Rei-x** [comment] 2022-09-02 16:04
I added option where you can customise who should be ignored from speech recognition in #41 
You could do something like this to ignore all bots except yours:
```js
addSpeechEvent(client, {
  shouldProcessSpeech: (user) => {
    if (user.bot && user.username !== "Your bot name") {
      return false;
    }
    return true;
  }
}
```
Is this what you want?

**Comment by Zoom-Developer** [comment] 2022-09-02 16:12
Thanks, yes! I'm not sure if it's worth posting here, but I thought I'd say it straight in this question, I found a bug where sometimes the speech is called multiple times, with slightly changed content, which is not the best result. How can I fix this?

**Comment by Rei-x** [comment] 2022-09-02 16:15
Can you give a way of reproduction?

**Comment by Zoom-Developer** [comment] 2022-09-02 16:17
I don't know English very well, what do you mean by reproduction?

**Comment by Rei-x** [comment] 2022-09-02 16:26
When does this problem occur? Is it random or maybe after multiple people/bots joins the voice channel?

**Comment by Zoom-Developer** [comment] 2022-09-02 16:28
No, 1 person says and about once every 10-15 calls the call is repeated several times, I assume that this is somehow connected with Google's speech recognition

**Comment by Rei-x** [comment] 2022-09-02 17:10
Okay, I think I found the reason for this problem
```ts
const opusStream = receiver.subscribe(userId, {
        end: {
          behavior: EndBehaviorType.AfterSilence,
          duration: 1000,
        },
      });
```
Bot is waiting 1 second after someone has stopped speaking and when someone stops talking for specific time (more than 300ms, less than 1 second) the speaking event is fired again, but recent one is still listening for audio, so there are 2 speech events for one speaking session.
Don't worry if you don't understand it (it's really hard for me to explain it well), I will fix it as soon as possible.

**Comment by Zoom-Developer** [comment] 2022-09-02 17:11
Look forward to)

**Comment by Rei-x** [comment] 2022-09-02 18:04
Update discord-speech-recognition package, this issue should be fixed now and you can use this new option `shouldProcess` to listen only to your bot

**Comment by Zoom-Developer** [comment] 2022-09-02 18:05
Thanks

**Closed** 2022-09-03 04:37 UTC
